/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import edu.austral.dissis.chess.checkers.initializer.CheckersInitializer
import edu.austral.dissis.chess.checkers.promotion.CheckersPromotionStrategy
import edu.austral.dissis.chess.checkers.rules.CheckersMovementRules
import edu.austral.dissis.chess.gui.*
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage
import edu.austral.dissis.chess.common.game.ApeEngine
import edu.austral.dissis.chess.common.rules.RulesImpl
import edu.austral.dissis.chess.mychess.promotion.ChessPromotionStrategy
import edu.austral.dissis.chess.mychess.rules.ChessMovementRules
import edu.austral.dissis.chess.mychess.initializer.CapaBlancaInitializer
import edu.austral.dissis.chess.mychess.initializer.ChessInitializer


fun main() {
    launch(ChessGameApplication::class.java)
}

class ChessGameApplication : Application() {
//    private val gameEngine = ApeEngine(RulesImpl(ChessInitializer(), ChessMovementRules(), ChessPromotionStrategy()))
//    private val gameEngine = ApeEngine(RulesImpl(CapaBlancaInitializer(), ChessMovementRules(), ChessPromotionStrategy()))
//    private val gameEngine = ApeEngine(RulesImpl(JediKnightsInitializer(), ChessMovementRules(), ChessPromotionStrategy()))
    private val gameEngine = ApeEngine(RulesImpl(CheckersInitializer(), CheckersMovementRules(), CheckersPromotionStrategy()))
    private val imageResolver = CachedImageResolver(DefaultImageResolver())

    companion object {
        const val GameTitle = "Chess"
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GameTitle
        val root = createGameViewFrom(gameEngine, imageResolver)
        primaryStage.scene = Scene(root)
        root.handleInitialState(gameEngine.init())
        primaryStage.show()
    }
}